### ISSUE TITLE
Possible OGL release?

### ISSUE THREAD

**Issue by ndo360** [ludus-leonis/nipajin#5]
Greetings!

I love the RPG system you developed and really enjoy the simplicity. I was curious if an OGL release would be considered as that would allow remixing with other OGL mechanics and ensuring that said remixes are under ‘open content’ as per the OGL license.

Cheers. :)

**Comment by ludus-leonis** [comment]
Thanks & sorry for the laaate reply. I initially considered OGL, but it requires its legal text to be included in each work ... around two A4 pages micro-print! NIP'AJIN itself is shorter :) For that reason I opted for the CC which can satisfy the license via a short block/link, as it is a no-go for leaflet RPGs nor NIP'AJIN Shots, which are only 1-2 A5 pages.
